cache = {
    "EmployerProfile:2070496": {"id": 2070496, "__typename": "EmployerProfile"},
    "ROOT_QUERY": {
        "__typename": "Query",
        'employer({"id":4189745})': {"__ref": "Employer:4189745"},
        'reviewCategories({"employerReviewsInput":{"employer":{"id":4189745}}})': [],
        'employerReviewsRG({"employerReviewsInput":{"applyDefaultCriteria":true,"dynamicProfileId":2070496,"employer":{"id":4189745},"employmentStatuses":[],"goc":null,"highlight":null,"jobTitle":null,"language":"eng","location":{"cityId":null,"countryId":null,"metroId":null,"stateId":null},"onlyCurrentEmployees":false,"page":{"num":1,"size":10},"preferredTldId":0,"sort":"RELEVANCE","useRowProfileTldForRatings":false,"worldwideFilter":false}})': {
            "__typename": "EmployerReviewsRG",
            "filteredReviewsCountByLang": [
                {
                    "__typename": "ReviewsCountByLanguage",
                    "count": 16,
                    "isoLanguage": "eng",
                }
            ],
            "employer": {"__ref": "Employer:4189745"},
            "queryLocation": None,
            "queryJobTitle": None,
            "currentPage": 1,
            "numberOfPages": 2,
            "lastReviewDateTime": "2023-07-04T14:14:12.290",
            "allReviewsCount": 16,
            "ratedReviewsCount": 16,
            "filteredReviewsCount": 16,
            "ratings": {
                "__typename": "EmployerRatings",
                "overallRating": 2.8,
                "reviewCount": 16,
                "ceoRating": -1,
                "recommendToFriendRating": 0.59,
                "cultureAndValuesRating": 2.9,
                "diversityAndInclusionRating": 3,
                "careerOpportunitiesRating": 3.2,
                "workLifeBalanceRating": 3.7,
                "seniorManagementRating": 2.8,
                "compensationAndBenefitsRating": 2.8,
                "businessOutlookRating": 0.4,
                "ceoRatingsCount": 0,
                "ratedCeo": None,
            },
            "reviews": [
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 51466166,
                    "reviewDateTime": "2021-08-22T17:06:09.807",
                    "ratingOverall": 5,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": "NEUTRAL",
                    "ratingWorkLifeBalance": 5,
                    "ratingCultureAndValues": 1,
                    "ratingDiversityAndInclusion": 1,
                    "ratingSeniorLeadership": 1,
                    "ratingRecommendToFriend": "POSITIVE",
                    "ratingCareerOpportunities": 5,
                    "ratingCompensationAndBenefits": 1,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": False,
                    "lengthOfEmployment": 0,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": 2020,
                    "jobTitle": {"__ref": "JobTitle:15225"},
                    "location": {"__ref": "City:1146962"},
                    "originalLanguageId": None,
                    "pros": "I got the chance to learn and explore around different sectors, and innovations. The working environment was conducive for accelerating teamwork and productivity. I'm glad I work there.",
                    "prosOriginal": None,
                    "cons": "I believe there should more employment benefits targeted towards life warfare and wellness.",
                    "consOriginal": None,
                    "summary": "Top Notch Company To Build Career Growth And Wealth.",
                    "summaryOriginal": None,
                    "advice": None,
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 0,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 1,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 75326296,
                    "reviewDateTime": "2023-04-09T13:00:31.367",
                    "ratingOverall": 2,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": None,
                    "ratingWorkLifeBalance": 0,
                    "ratingCultureAndValues": 0,
                    "ratingDiversityAndInclusion": 0,
                    "ratingSeniorLeadership": 0,
                    "ratingRecommendToFriend": None,
                    "ratingCareerOpportunities": 0,
                    "ratingCompensationAndBenefits": 0,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": True,
                    "lengthOfEmployment": 0,
                    "employmentStatus": "CONTRACT",
                    "jobEndingYear": None,
                    "jobTitle": None,
                    "location": {"__ref": "City:1132348"},
                    "originalLanguageId": None,
                    "pros": "The pay was subpar at best.",
                    "prosOriginal": None,
                    "cons": "They could offer remote work",
                    "consOriginal": None,
                    "summary": "it's okay",
                    "summaryOriginal": None,
                    "advice": None,
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 0,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 3,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 77956742,
                    "reviewDateTime": "2023-07-04T14:14:12.290",
                    "ratingOverall": 5,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": "NEUTRAL",
                    "ratingWorkLifeBalance": 5,
                    "ratingCultureAndValues": 5,
                    "ratingDiversityAndInclusion": 5,
                    "ratingSeniorLeadership": 4,
                    "ratingRecommendToFriend": "POSITIVE",
                    "ratingCareerOpportunities": 4,
                    "ratingCompensationAndBenefits": 4,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": False,
                    "lengthOfEmployment": 2,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": 2019,
                    "jobTitle": {"__ref": "JobTitle:44045"},
                    "location": {"__ref": "City:2671300"},
                    "originalLanguageId": None,
                    "pros": "Great place to work and a great company to grow with",
                    "prosOriginal": None,
                    "cons": "No real issues working here",
                    "consOriginal": None,
                    "summary": "Great place to work",
                    "summaryOriginal": None,
                    "advice": None,
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 0,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 2,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 70112029,
                    "reviewDateTime": "2022-10-13T09:35:20.397",
                    "ratingOverall": 1,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": None,
                    "ratingWorkLifeBalance": 0,
                    "ratingCultureAndValues": 0,
                    "ratingDiversityAndInclusion": 0,
                    "ratingSeniorLeadership": 0,
                    "ratingRecommendToFriend": None,
                    "ratingCareerOpportunities": 0,
                    "ratingCompensationAndBenefits": 0,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": False,
                    "lengthOfEmployment": 1,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": 2022,
                    "jobTitle": {"__ref": "JobTitle:50731"},
                    "location": {"__ref": "City:2675154"},
                    "originalLanguageId": None,
                    "pros": "The office location is lovely",
                    "prosOriginal": None,
                    "cons": "- Too many product issues. Departments are all understaffed so it is taking longer than necessary for issues to be resolved. \r\n- No processes to resolve said issues. Each problem is continuously passed on from department to department. \r\n- Base salary is far too low compared to job expectations. \r\n- No mention of support for Black History Month, yet other minority months are supported. \r\n- Expected to charge accounts a certain rate for packages, but then too many discounts are applied. \r\n- They refuse to increase the salary but put a job posting out offering more than the basic salary for Senior Account Managers. \r\n- There isn’t enough time to train the new starters. \r\n- There’s an internal training scheme for staff who are interested in becoming managers, but if you miss a session (a single session) due to situations out of your control, you’re taken off the course. \r\n- Overall completely unorganised, unprofessional company.",
                    "consOriginal": None,
                    "summary": "Wouldn’t recommend…",
                    "summaryOriginal": None,
                    "advice": "- If you believe that your product works then why are you allowing so many discounts to be applied to packages? \r\n- Why aren’t teams made aware of the emails that are sent to customers? \r\n- Acknowledge the Senior job posting in company meetings properly. You have dealt with it in a very sly manner. \r\n- Be clear on what you expect Account Managers to prioritise. \r\n- Create a better training plan for new starters and the management course \r\n- Basic salary increase",
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 1,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 1,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 75146890,
                    "reviewDateTime": "2023-04-03T10:29:46.420",
                    "ratingOverall": 3,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": None,
                    "ratingWorkLifeBalance": 0,
                    "ratingCultureAndValues": 0,
                    "ratingDiversityAndInclusion": 0,
                    "ratingSeniorLeadership": 0,
                    "ratingRecommendToFriend": None,
                    "ratingCareerOpportunities": 0,
                    "ratingCompensationAndBenefits": 0,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": False,
                    "lengthOfEmployment": 4,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": 2021,
                    "jobTitle": {"__ref": "JobTitle:15225"},
                    "location": {"__ref": "City:3380432"},
                    "originalLanguageId": None,
                    "pros": "Friendly atmosphere and well supplied offices",
                    "prosOriginal": None,
                    "cons": "Not great accountability for management",
                    "consOriginal": None,
                    "summary": "Nice enough",
                    "summaryOriginal": None,
                    "advice": None,
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 0,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 2,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 74453879,
                    "reviewDateTime": "2023-03-13T04:53:37.343",
                    "ratingOverall": 3,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": "POSITIVE",
                    "ratingWorkLifeBalance": 3,
                    "ratingCultureAndValues": 3,
                    "ratingDiversityAndInclusion": 3,
                    "ratingSeniorLeadership": 3,
                    "ratingRecommendToFriend": "POSITIVE",
                    "ratingCareerOpportunities": 2,
                    "ratingCompensationAndBenefits": 3,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": False,
                    "lengthOfEmployment": 1,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": 2023,
                    "jobTitle": {"__ref": "JobTitle:50838"},
                    "location": {"__ref": "City:2671300"},
                    "originalLanguageId": None,
                    "pros": "Working from home 3 days a week",
                    "prosOriginal": None,
                    "cons": "Cold calling and job repetition. Also no room for progression",
                    "consOriginal": None,
                    "summary": "Emg",
                    "summaryOriginal": None,
                    "advice": None,
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 0,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 2,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 71669873,
                    "reviewDateTime": "2022-12-06T16:40:52.667",
                    "ratingOverall": 1,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": "NEGATIVE",
                    "ratingWorkLifeBalance": 1,
                    "ratingCultureAndValues": 1,
                    "ratingDiversityAndInclusion": 1,
                    "ratingSeniorLeadership": 1,
                    "ratingRecommendToFriend": "NEGATIVE",
                    "ratingCareerOpportunities": 1,
                    "ratingCompensationAndBenefits": 1,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": False,
                    "lengthOfEmployment": 1,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": 2022,
                    "jobTitle": {"__ref": "JobTitle:270488"},
                    "location": {"__ref": "City:2675154"},
                    "originalLanguageId": None,
                    "pros": "My team, stocked fridge during office days and hybrid work from home",
                    "prosOriginal": None,
                    "cons": "Management - they do not treat you as employees but rather as robots who they don’t want to have any personality. Your main job is to answer phones, this job is a glorified call centre but the job description will tell you otherwise. You are not allowed to take lunch as a team, you’re not allowed to attend company wide meetings as a team, all because you are constantly asked to stay on the phones at all time, management will make you feel bad about going to the bathroom or grabbing a coffee.",
                    "consOriginal": None,
                    "summary": "Avoid if you care about your mental well-being",
                    "summaryOriginal": None,
                    "advice": "Take your feedback on board, there is a reason this company was failing and such need for these drastic changes. Your employees are not robots, treat them with divinity!",
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 1,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 2,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 73117556,
                    "reviewDateTime": "2023-01-29T23:30:26.573",
                    "ratingOverall": 1,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": "NEGATIVE",
                    "ratingWorkLifeBalance": 1,
                    "ratingCultureAndValues": 1,
                    "ratingDiversityAndInclusion": 1,
                    "ratingSeniorLeadership": 1,
                    "ratingRecommendToFriend": "NEGATIVE",
                    "ratingCareerOpportunities": 1,
                    "ratingCompensationAndBenefits": 1,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": True,
                    "lengthOfEmployment": 2,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": None,
                    "jobTitle": {"__ref": "JobTitle:270488"},
                    "location": {"__ref": "City:2675154"},
                    "originalLanguageId": None,
                    "pros": "Office location was really nice",
                    "prosOriginal": None,
                    "cons": "If you are a honest person just trying to make a living, avoid this place like the plague. Business built upon manipulative management that refuse to be honest with you. Customer Service role disguised as customer success role to bring in more recruitment however you are stalling your own career progression as nothing about this role is customer success related. No matter what you do, your value as an employee is measured by inbound call rates. No motivation or morale building, however management quick to talk down on you when one call is missed during busy periods with less than normal staff. Refusing to give promotions but advertising roles at higher salary and claim that these are in line with their competency framework, however belittle and gaslight you when you show examples of this. The minute you show any autonomy or progression management look for ways to shift the goalpost so you look like you’re underperforming and a way to push you out No training in place so all left to team members to support and train new staff, because both team lead and managers ignore your messages all day, but then they berate you for sending too many messages. Refusal to listen about ways to improve service or product, look at you like a number rather than an employee to be spoken at - this is not a collaborative environment at all Include technical errors such as phone cut outs or automatic case raising when kpi measuring so you never reach your target for bonus Don’t speak to HR about anything you’re worried about as in turn management will retaliate and team leads in different departments will know about it and make you feel like you’re in the wrong Management try and act intimidating the minute you speak out about things that aren’t right within the business There is constantly a scapegoat as management and team leads will never take responsibility as this makes them look bad to the investors You’re told that you do not deserve pay rises and that no progression can be offered",
                    "consOriginal": None,
                    "summary": "Avoid this place if you value yourself",
                    "summaryOriginal": None,
                    "advice": "Look at all the cons and figure it out yourself the same way your staff have to figure everything out themselves.",
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 6,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 2,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 69406948,
                    "reviewDateTime": "2022-09-24T10:22:52.130",
                    "ratingOverall": 5,
                    "ratingCeo": "APPROVE",
                    "ratingBusinessOutlook": "POSITIVE",
                    "ratingWorkLifeBalance": 4,
                    "ratingCultureAndValues": 3,
                    "ratingDiversityAndInclusion": 3,
                    "ratingSeniorLeadership": 3,
                    "ratingRecommendToFriend": "POSITIVE",
                    "ratingCareerOpportunities": 5,
                    "ratingCompensationAndBenefits": 4,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": False,
                    "lengthOfEmployment": 0,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": 2020,
                    "jobTitle": None,
                    "location": None,
                    "originalLanguageId": None,
                    "pros": "Good people working at this company",
                    "prosOriginal": None,
                    "cons": "The bar on performance is set very high",
                    "consOriginal": None,
                    "summary": "Good stuff",
                    "summaryOriginal": None,
                    "advice": None,
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 0,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 7,
                    "languageId": "eng",
                    "translationMethod": None,
                },
                {
                    "__typename": "EmployerReviewRG",
                    "isLegal": True,
                    "reviewId": 71331461,
                    "reviewDateTime": "2022-11-23T06:18:03.793",
                    "ratingOverall": 2,
                    "ratingCeo": None,
                    "ratingBusinessOutlook": None,
                    "ratingWorkLifeBalance": 0,
                    "ratingCultureAndValues": 0,
                    "ratingDiversityAndInclusion": 0,
                    "ratingSeniorLeadership": 0,
                    "ratingRecommendToFriend": None,
                    "ratingCareerOpportunities": 0,
                    "ratingCompensationAndBenefits": 0,
                    "employer": {"__ref": "Employer:4189745"},
                    "isCurrentJob": False,
                    "lengthOfEmployment": 0,
                    "employmentStatus": "REGULAR",
                    "jobEndingYear": 2021,
                    "jobTitle": {"__ref": "JobTitle:15225"},
                    "location": {"__ref": "City:2671300"},
                    "originalLanguageId": None,
                    "pros": "Nice people and good perks",
                    "prosOriginal": None,
                    "cons": "Management was poor. Moving targets and just tell you try harder.",
                    "consOriginal": None,
                    "summary": "Poor management",
                    "summaryOriginal": None,
                    "advice": None,
                    "adviceOriginal": None,
                    "isLanguageMismatch": False,
                    "countHelpful": 0,
                    "countNotHelpful": 0,
                    "employerResponses": [],
                    "featured": False,
                    "isCovid19": False,
                    "topLevelDomainId": 1,
                    "languageId": "eng",
                    "translationMethod": None,
                },
            ],
            "ratingCountDistribution": {
                "__typename": "RatingCountDistribution",
                "overall": {
                    "__typename": "FiveStarRatingCountDistribution",
                    "_5": 6,
                    "_4": 0,
                    "_3": 3,
                    "_2": 2,
                    "_1": 5,
                },
                "cultureAndValues": {
                    "__typename": "FiveStarRatingCountDistribution",
                    "_5": 3,
                    "_4": 1,
                    "_3": 3,
                    "_2": 1,
                    "_1": 3,
                },
                "careerOpportunities": {
                    "__typename": "FiveStarRatingCountDistribution",
                    "_5": 5,
                    "_4": 1,
                    "_3": 1,
                    "_2": 1,
                    "_1": 3,
                },
                "workLifeBalance": {
                    "__typename": "FiveStarRatingCountDistribution",
                    "_5": 5,
                    "_4": 3,
                    "_3": 1,
                    "_2": 0,
                    "_1": 2,
                },
                "seniorManagement": {
                    "__typename": "FiveStarRatingCountDistribution",
                    "_5": 2,
                    "_4": 3,
                    "_3": 2,
                    "_2": 0,
                    "_1": 4,
                },
                "compensationAndBenefits": {
                    "__typename": "FiveStarRatingCountDistribution",
                    "_5": 2,
                    "_4": 3,
                    "_3": 1,
                    "_2": 2,
                    "_1": 3,
                },
                "diversityAndInclusion": {
                    "__typename": "FiveStarRatingCountDistribution",
                    "_5": 3,
                    "_4": 1,
                    "_3": 4,
                    "_2": 0,
                    "_1": 3,
                },
                "recommendToFriend": {
                    "__typename": "RecommendToFriendRatingCountDistribution",
                    "WONT_RECOMMEND": 4,
                    "RECOMMEND": 7,
                },
            },
        },
        "pageViewSummary": {"__typename": "PageViewSummary", "totalCount": 0},
        'reviewLocationsV2({"employer":{"id":4189745}})': {
            "__typename": "ReviewLocationsV2",
            "locations": [
                {"__ref": "ReviewLocationsV2Item:1"},
                {"__ref": "ReviewLocationsV2Item:2280"},
                {"__ref": "ReviewLocationsV2Item:602"},
                {"__ref": "ReviewLocationsV2Item:1146962"},
                {"__ref": "ReviewLocationsV2Item:428"},
                {"__ref": "ReviewLocationsV2Item:615"},
                {"__ref": "ReviewLocationsV2Item:1132348"},
                {"__ref": "ReviewLocationsV2Item:2"},
                {"__ref": "ReviewLocationsV2Item:7287"},
                {"__ref": "ReviewLocationsV2Item:1037"},
                {"__ref": "ReviewLocationsV2Item:2687487"},
                {"__ref": "ReviewLocationsV2Item:1035"},
                {"__ref": "ReviewLocationsV2Item:2675154"},
                {"__ref": "ReviewLocationsV2Item:2671300"},
                {"__ref": "ReviewLocationsV2Item:1168"},
                {"__ref": "ReviewLocationsV2Item:3380432"},
                {"__ref": "ReviewLocationsV2Item:115"},
                {"__ref": "ReviewLocationsV2Item:12207"},
                {"__ref": "ReviewLocationsV2Item:1076"},
                {"__ref": "ReviewLocationsV2Item:2865319"},
            ],
            "employerHQLocation": {"__ref": "ReviewLocationsV2Item:2671300"},
        },
        'faqQuestionsByEmployer({"employerId":4189745})': {
            "__typename": "FaqResponse",
            "totalQuestions": 14,
        },
        'demographicRatingsRG({"employerId":4189745})': [
            {
                "__typename": "DemographicRatings",
                "category": "gender",
                "categoryRatings": [
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "man",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "woman",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "nonBinary",
                        "ratings": None,
                    },
                ],
            },
            {
                "__typename": "DemographicRatings",
                "category": "raceEthnicity",
                "categoryRatings": [
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "indigenousAmerican",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "asian",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "nativeHawaiian",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "middleEastern",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "blackOrAfricanAmerican",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "hispanicOrLatinx",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "white",
                        "ratings": None,
                    },
                ],
            },
            {
                "__typename": "DemographicRatings",
                "category": "sexualOrientation",
                "categoryRatings": [
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "yes",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "no",
                        "ratings": None,
                    },
                ],
            },
            {
                "__typename": "DemographicRatings",
                "category": "disability",
                "categoryRatings": [
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "yes",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "no",
                        "ratings": None,
                    },
                ],
            },
            {
                "__typename": "DemographicRatings",
                "category": "parentOrCaregiver",
                "categoryRatings": [
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "parentOrGuardian",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "caregiver",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "no",
                        "ratings": None,
                    },
                ],
            },
            {
                "__typename": "DemographicRatings",
                "category": "veteranStatus",
                "categoryRatings": [
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "yes",
                        "ratings": None,
                    },
                    {
                        "__typename": "DemographicCategoryValueRatings",
                        "categoryValue": "no",
                        "ratings": None,
                    },
                ],
            },
        ],
        'seoRecommendations({"cityId":null,"gdContext":"salaries"})': {
            "__typename": "SeoRecommendations",
            "recommendations": [
                {"__ref": "SeoRecommendationItem:100369"},
                {"__ref": "SeoRecommendationItem:102211"},
                {"__ref": "SeoRecommendationItem:100063"},
                {"__ref": "SeoRecommendationItem:100198"},
                {"__ref": "SeoRecommendationItem:100116"},
                {"__ref": "SeoRecommendationItem:100078"},
                {"__ref": "SeoRecommendationItem:100165"},
                {"__ref": "SeoRecommendationItem:100081"},
                {"__ref": "SeoRecommendationItem:100167"},
                {"__ref": "SeoRecommendationItem:100169"},
                {"__ref": "SeoRecommendationItem:100099"},
                {"__ref": "SeoRecommendationItem:100523"},
                {"__ref": "SeoRecommendationItem:100441"},
                {"__ref": "SeoRecommendationItem:100005"},
                {"__ref": "SeoRecommendationItem:100505"},
                {"__ref": "SeoRecommendationItem:102465"},
                {"__ref": "SeoRecommendationItem:100375"},
                {"__ref": "SeoRecommendationItem:100011"},
                {"__ref": "SeoRecommendationItem:102609"},
                {"__ref": "SeoRecommendationItem:100065"},
            ],
        },
        'getBowlPosts({"request":{"bowlId":"5fd38d89b5703e00295fe042","page":{"count":3},"sort":{"sortType":"RECENCY"}}})': {
            "__typename": "GlassbowlFeed",
            "items": [
                {"__ref": "FishbowlPost:65a5220f8680cfb784dad495"},
                {"__ref": "FishbowlPost:65a509251768252d518002f4"},
                {"__ref": "FishbowlPost:65a49e1d43567d41df7fd83a"},
            ],
        },
        'fishbowlPostsForEmployer({"employer":{"id":4189745},"ner":true})': {
            "__typename": "FishbowlPosts",
            "resultsType": "none",
            "feedRecommendation": None,
            "posts": [],
        },
        'fishbowlPostsForEmployer({"employer":{"id":4189745,"name":"eBay Motors Group"},"ner":true})': {
            "__typename": "FishbowlPosts",
            "resultsType": "none",
            "feedRecommendation": None,
            "posts": [],
        },
        'mlReviewHighlightsRG({"employerId":4189745})': {
            "__typename": "MLReviewHighlights",
            "pros": [],
            "cons": [
                {
                    "__typename": "MLReviewHighlight",
                    "phrase": "however management",
                    "aspect": "management",
                    "sentence": "No motivation or morale building, however management quick to talk down on you when one call is missed during busy periods with less than normal staff.",
                    "reviewCount": 4,
                    "highlightSpans": [
                        {"__typename": "TextSpan", "position": 34, "length": 18}
                    ],
                }
            ],
        },
        'trendDataGivenStartAndEndYearMonthRG({"trendDataInput":{"employer":{"id":4189745},"monthCount":12}})': [
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 3,
                "compAndBenefitsRatingPercentChangeOverTime": 4,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 3,
                "compAndBenefitsRatingPercentChangeOverTime": 4,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 3,
                "compAndBenefitsRatingPercentChangeOverTime": 4,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 3,
                "compAndBenefitsRatingPercentChangeOverTime": 4,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 2,
                "compAndBenefitsRatingPercentChangeOverTime": 4,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 2,
                "compAndBenefitsRatingPercentChangeOverTime": 4,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 2,
                "compAndBenefitsRatingPercentChangeOverTime": 4,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 0,
                "compAndBenefitsRatingPercentChangeOverTime": 1,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 0,
                "compAndBenefitsRatingPercentChangeOverTime": 1,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 0,
                "compAndBenefitsRatingPercentChangeOverTime": 1,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 0,
                "compAndBenefitsRatingPercentChangeOverTime": 1,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 0,
                "compAndBenefitsRatingPercentChangeOverTime": 0,
            },
            {
                "__typename": "EmployerRatingsWrapperV2",
                "overallRatingPercentChangeOverTime": 0,
                "compAndBenefitsRatingPercentChangeOverTime": 0,
            },
        ],
        'faqTopicsByEmployerAndSentiment({"employerId":4189745})': {
            "__typename": "ProsAndConsWrapper",
            "pros": [
                {"__typename": "ProsAndConsType", "name": "benefits", "docCount": 2},
                {"__typename": "ProsAndConsType", "name": "culture", "docCount": 1},
                {"__typename": "ProsAndConsType", "name": "coworkers", "docCount": 4},
                {
                    "__typename": "ProsAndConsType",
                    "name": "compensation",
                    "docCount": 3,
                },
                {"__typename": "ProsAndConsType", "name": "workplace", "docCount": 3},
                {
                    "__typename": "ProsAndConsType",
                    "name": "workLifeBalance",
                    "docCount": 1,
                },
            ],
            "cons": [
                {
                    "__typename": "ProsAndConsType",
                    "name": "careerDevelopment",
                    "docCount": 7,
                },
                {"__typename": "ProsAndConsType", "name": "management", "docCount": 13},
            ],
        },
        'seoRecommendations({"cityId":null,"employerId":4189745,"gdContext":"salaries"})': {
            "__typename": "SeoRecommendations",
            "recommendations": [],
        },
    },
    "EmployerManagedContent:{}": {
        "__typename": "EmployerManagedContent",
        "isContentPaidForTld": False,
        "featuredVideoLink": None,
        "profileCoverPhoto": None,
        "diversityContent": {
            "__typename": "DiversityAndInclusionContent",
            "programsAndInitiatives": None,
        },
    },
    "Employer:4189745": {
        "id": 4189745,
        "__typename": "Employer",
        "legalActionBadges": [],
        'bestPlacesToWork({"onlyCurrent":true})': [],
        "bestProfile": {"__ref": "EmployerProfile:2070496"},
        "ceo": None,
        'employerManagedContent({"parameters":[{"divisionProfileId":2070496,"employerId":4189745}]})': [
            {"__ref": "EmployerManagedContent:{}"}
        ],
        'squareLogoUrl({"size":"LARGE"})': None,
        "links": {
            "__typename": "EiEmployerLinks",
            "jobsUrl": "/Jobs/eBay-Motors-Group-Jobs-E4189745.htm",
            "reviewsUrl": "/Reviews/eBay-Motors-Group-Reviews-E4189745.htm",
            "faqUrl": "/FAQ/eBay-Motors-Group-Questions-E4189745.htm",
            "benefitsUrl": "/Benefits/eBay-Motors-Group-Benefits-E4189745.htm",
            "interviewUrl": "/Interview/eBay-Motors-Group-Interview-Questions-E4189745.htm",
            "locationsUrl": "/Location/All-eBay-Motors-Group-Office-Locations-E4189745.htm",
            "orgStructureUrl": "/Affiliated/eBay-Motors-Group-Companies-E4189745.htm",
            "overviewUrl": "/Overview/Working-at-eBay-Motors-Group-EI_IE4189745.11,28.htm",
            "photosUrl": "/Photos/eBay-Motors-Group-Office-Photos-E4189745.htm",
            "salariesUrl": "/Salary/eBay-Motors-Group-Salaries-E4189745.htm",
        },
        'squareLogoUrl({"size":"REGULAR"})': None,
        "shortName": "eBay Motors Group",
        "squareLogoUrl": None,
        "website": "www.ebaymotorsgroup.co.uk",
        "activeStatus": "INACTIVE",
        "coverPhoto": {"__typename": "EmployerCoverPhoto", "hiResUrl": None},
        "counts": {
            "__typename": "EmployerCounts",
            "benefitCount": 1,
            "globalJobCount": {"__typename": "EmployerJobCountHolder", "jobCount": 0},
            "interviewCount": 1,
            "photoCount": None,
            "reviewCount": 16,
            "salaryCount": 33,
        },
        "requirementsComplete": False,
        "officeAddresses": [],
        "parent": None,
        "ratings": {
            "__typename": "DefaultEmployerRatings",
            "diversityAndInclusionRatingCount": 11,
        },
        "subsidiaries": [],
    },
    "JobTitle:15225": {
        "id": 15225,
        "__typename": "JobTitle",
        "text": "Account Manager",
    },
    "City:1146962": {
        "id": 1146962,
        "__typename": "City",
        "type": "CITY",
        "name": "American Canyon, CA",
    },
    "City:1132348": {
        "id": 1132348,
        "__typename": "City",
        "type": "CITY",
        "name": "New York, NY",
    },
    "JobTitle:44045": {"id": 44045, "__typename": "JobTitle", "text": "Sales Ops"},
    "City:2671300": {
        "id": 2671300,
        "__typename": "City",
        "type": "CITY",
        "name": "London, England",
    },
    "JobTitle:50731": {
        "id": 50731,
        "__typename": "JobTitle",
        "text": "Sales Account Manager",
    },
    "City:2675154": {
        "id": 2675154,
        "__typename": "City",
        "type": "CITY",
        "name": "Richmond, London, England",
    },
    "City:3380432": {
        "id": 3380432,
        "__typename": "City",
        "type": "CITY",
        "name": "Abingdon, England",
    },
    "JobTitle:50838": {
        "id": 50838,
        "__typename": "JobTitle",
        "text": "Sales Associate",
    },
    "JobTitle:270488": {
        "id": 270488,
        "__typename": "JobTitle",
        "text": "Customer Success Executive",
    },
    "ReviewLocationsV2Item:1": {
        "id": 1,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "N",
        "name": "United States",
    },
    "ReviewLocationsV2Item:2280": {
        "id": 2280,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "S",
        "name": "California",
    },
    "ReviewLocationsV2Item:602": {
        "id": 602,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "M",
        "name": "Napa, CA",
    },
    "ReviewLocationsV2Item:1146962": {
        "id": 1146962,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "C",
        "name": "American Canyon, CA",
    },
    "ReviewLocationsV2Item:428": {
        "id": 428,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "S",
        "name": "New York State",
    },
    "ReviewLocationsV2Item:615": {
        "id": 615,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "M",
        "name": "New York City, NY",
    },
    "ReviewLocationsV2Item:1132348": {
        "id": 1132348,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "C",
        "name": "New York, NY",
    },
    "ReviewLocationsV2Item:2": {
        "id": 2,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "N",
        "name": "United Kingdom",
    },
    "ReviewLocationsV2Item:7287": {
        "id": 7287,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "S",
        "name": "England",
    },
    "ReviewLocationsV2Item:1037": {
        "id": 1037,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "M",
        "name": "Reading, United Kingdom",
    },
    "ReviewLocationsV2Item:2687487": {
        "id": 2687487,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "C",
        "name": "Basingstoke, England",
    },
    "ReviewLocationsV2Item:1035": {
        "id": 1035,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "M",
        "name": "London, United Kingdom",
    },
    "ReviewLocationsV2Item:2675154": {
        "id": 2675154,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "C",
        "name": "Richmond, London, England",
    },
    "ReviewLocationsV2Item:2671300": {
        "id": 2671300,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "C",
        "name": "London, England",
    },
    "ReviewLocationsV2Item:1168": {
        "id": 1168,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "M",
        "name": "Oxford, United Kingdom",
    },
    "ReviewLocationsV2Item:3380432": {
        "id": 3380432,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "C",
        "name": "Abingdon, England",
    },
    "ReviewLocationsV2Item:115": {
        "id": 115,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "N",
        "name": "India",
    },
    "ReviewLocationsV2Item:12207": {
        "id": 12207,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "S",
        "name": "Telangana",
    },
    "ReviewLocationsV2Item:1076": {
        "id": 1076,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "M",
        "name": "Hyderabad, India",
    },
    "ReviewLocationsV2Item:2865319": {
        "id": 2865319,
        "__typename": "ReviewLocationsV2Item",
        "atlasType": "C",
        "name": "Hyderābād",
    },
    "SeoRecommendationItem:100369": {
        "id": 100369,
        "__typename": "SeoRecommendationItem",
        "name": "Administrative Assistant",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:102211": {
        "id": 102211,
        "__typename": "SeoRecommendationItem",
        "name": "Customer Relations",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100063": {
        "id": 100063,
        "__typename": "SeoRecommendationItem",
        "name": "Software Engineer",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100198": {
        "id": 100198,
        "__typename": "SeoRecommendationItem",
        "name": "Accountant",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100116": {
        "id": 100116,
        "__typename": "SeoRecommendationItem",
        "name": "Data Analyst",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100078": {
        "id": 100078,
        "__typename": "SeoRecommendationItem",
        "name": "Project Manager",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100165": {
        "id": 100165,
        "__typename": "SeoRecommendationItem",
        "name": "Sales Representative",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100081": {
        "id": 100081,
        "__typename": "SeoRecommendationItem",
        "name": "Graphic Designer",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100167": {
        "id": 100167,
        "__typename": "SeoRecommendationItem",
        "name": "Software Developer",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100169": {
        "id": 100169,
        "__typename": "SeoRecommendationItem",
        "name": "Business Analyst",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100099": {
        "id": 100099,
        "__typename": "SeoRecommendationItem",
        "name": "Receptionist",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100523": {
        "id": 100523,
        "__typename": "SeoRecommendationItem",
        "name": "Data Scientist",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100441": {
        "id": 100441,
        "__typename": "SeoRecommendationItem",
        "name": "Driver",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100005": {
        "id": 100005,
        "__typename": "SeoRecommendationItem",
        "name": "Operations Manager",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100505": {
        "id": 100505,
        "__typename": "SeoRecommendationItem",
        "name": "HR Generalist",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:102465": {
        "id": 102465,
        "__typename": "SeoRecommendationItem",
        "name": "Engineer",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100375": {
        "id": 100375,
        "__typename": "SeoRecommendationItem",
        "name": "Finance Manager",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100011": {
        "id": 100011,
        "__typename": "SeoRecommendationItem",
        "name": "Registered Nurse",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:102609": {
        "id": 102609,
        "__typename": "SeoRecommendationItem",
        "name": "Manager",
        "pageSegment": "O",
    },
    "SeoRecommendationItem:100065": {
        "id": 100065,
        "__typename": "SeoRecommendationItem",
        "name": "Mechanical Engineer",
        "pageSegment": "O",
    },
    "Bowl:5fd38d89b5703e00295fe042": {
        "id": "5fd38d89b5703e00295fe042",
        "__typename": "Bowl",
        "description": "Feel free to post any interview questions you might be asked and I’ll help you compose an effective response :)",
        "handleUrl": "interview-tips",
        "memberCount": 221250,
        "name": "Interview Tips",
        "uiConfig": {
            "__typename": "BowlUiConfig",
            "coverPic": {
                "__typename": "FishbowlPicture",
                "imageUrl": "https://dslntlv9vhjr4.cloudfront.net/crowd_images/interview-tips_gJFI5.png",
            },
        },
    },
    "FishbowlPost:65a5220f8680cfb784dad495": {
        "id": "65a5220f8680cfb784dad495",
        "__typename": "FishbowlPost",
        "bowl": {"__ref": "Bowl:5fd38d89b5703e00295fe042"},
        "author": {"__typename": "FishbowlSign", "name": "Regional Manager"},
        "commentsCount": 6,
        "creationDate": "2024-01-15T12:16:15.662Z",
        "handleUrl": "salarieshave-an-interview-this-morning-do-you-reference-the-person-interviewing-you-formally-as-mr-it-is-it-ok-to-use-his",
        "reactionsList": [
            {"__typename": "FishbowlReaction", "count": 1, "reactionType": "LIKE"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "HELPFUL"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "SMART"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "FUNNY"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "UPLIFTING"},
        ],
        "messageData": {
            "__typename": "FishbowlMessageData",
            "text": "Salaries\nHave an interview this morning. Do you reference the person interviewing you formally as Mr. it is it ok to use his first name?\nThanks much!",
        },
    },
    "FishbowlPost:65a509251768252d518002f4": {
        "id": "65a509251768252d518002f4",
        "__typename": "FishbowlPost",
        "bowl": {"__ref": "Bowl:5fd38d89b5703e00295fe042"},
        "author": {"__typename": "FishbowlSign", "name": "Software Developer"},
        "commentsCount": 0,
        "creationDate": "2024-01-15T10:29:57.980Z",
        "handleUrl": "hi-folksis-it-good-to-join-infosys-on-third-party-payroll-or-is-their-any-problem-in-future-opportunities-please-suggest",
        "reactionsList": [
            {"__typename": "FishbowlReaction", "count": 1, "reactionType": "LIKE"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "HELPFUL"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "SMART"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "FUNNY"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "UPLIFTING"},
        ],
        "messageData": {
            "__typename": "FishbowlMessageData",
            "text": "Hi folks\n\nIs it good to join Infosys on third party payroll or is their any problem in future opportunities. Please suggest me. Thanks in advance ",
        },
    },
    "FishbowlPost:65a49e1d43567d41df7fd83a": {
        "id": "65a49e1d43567d41df7fd83a",
        "__typename": "FishbowlPost",
        "bowl": {"__ref": "Bowl:5fd38d89b5703e00295fe042"},
        "author": {"__typename": "FishbowlSign", "name": "Morgan Stanley"},
        "commentsCount": 1,
        "creationDate": "2024-01-15T02:53:17.611Z",
        "handleUrl": "hi-all-if-i-get-through-multiple-rounds-of-interviews-for-a-position-at-a-company-get-rejected-would-it-be-ok-to-immediately",
        "reactionsList": [
            {"__typename": "FishbowlReaction", "count": 4, "reactionType": "LIKE"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "HELPFUL"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "SMART"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "FUNNY"},
            {"__typename": "FishbowlReaction", "count": 0, "reactionType": "UPLIFTING"},
        ],
        "messageData": {
            "__typename": "FishbowlMessageData",
            "text": "Hi All - If I get through multiple rounds of interviews for a position at a company & get rejected, would it be OK to immediately after submit applications at the same company for other positions (similar responsibilities but on a different team)? Or would I need to wait a few months? I work in the financial services industry (if that matters). Thanks for your help in advance!",
        },
    },
}
