company = [
    {
        "suggestion": "Amazon",
        "source": "GD_V2",
        "confidence": 2568.2256,
        "version": "NEW",
        "category": "company",
        "employerId": "6036",
        "logoUrl": "sqlm/6036/amazon-squarelogo-1552847650117.png",
        "indiaFlag": false,
        "recentPosts": 0,
        "directHit": true,
    },
    {
        "suggestion": "Amazon Delivery Driver",
        "source": "GD_V2",
        "confidence": 856.5546,
        "version": "NEW",
        "category": "multicat",
        "employerId": "6036",
        "logoUrl": "sqlm/6036/amazon-squarelogo-1552847650117.png",
        "indiaFlag": false,
        "recentPosts": 0,
        "directHit": false,
    },
    {
        "suggestion": "Amazon Warehouse",
        "source": "GD_V2",
        "confidence": 325.82935,
        "version": "NEW",
        "category": "company",
        "employerId": "8816758",
        "logoUrl": "sqlm/8816758/amazon-warehouse-squareLogo-1687905795323.png",
        "indiaFlag": false,
        "recentPosts": 0,
        "directHit": false,
    },
    {
        "suggestion": "Amazon Warehouse Worker",
        "source": "GD_V2",
        "confidence": 199.33853,
        "version": "NEW",
        "category": "multicat",
        "employerId": "6036",
        "logoUrl": "sqlm/6036/amazon-squarelogo-1552847650117.png",
        "indiaFlag": false,
        "recentPosts": 0,
        "directHit": false,
    },
    {
        "suggestion": "Amazon Web Services",
        "source": "GD_V2",
        "confidence": 41.134617,
        "version": "NEW",
        "category": "company",
        "employerId": "7470741",
        "logoUrl": "sqlm/7470741/amazon-web-services-squareLogo-1680754621463.png",
        "indiaFlag": false,
        "recentPosts": 0,
        "directHit": false,
    },
    {
        "suggestion": "Amazon Customer Service At Home",
        "source": "GD_V2",
        "confidence": 31.895119,
        "version": "NEW",
        "category": "jobtitle",
        "employerId": "0",
        "indiaFlag": false,
        "recentPosts": 0,
        "directHit": false,
    },
    {
        "suggestion": "Amazon Driver",
        "source": "GD_V2",
        "confidence": 26.416992,
        "version": "NEW",
        "category": "multicat",
        "employerId": "6036",
        "logoUrl": "sqlm/6036/amazon-squarelogo-1552847650117.png",
        "indiaFlag": false,
        "recentPosts": 0,
        "directHit": false,
    },
    {
        "suggestion": "Amazon Warehouse Associate",
        "source": "GD_V2",
        "confidence": 24.732042,
        "version": "NEW",
        "category": "multicat",
        "employerId": "6036",
        "logoUrl": "sqlm/6036/amazon-squarelogo-1552847650117.png",
        "indiaFlag": false,
        "recentPosts": 0,
        "directHit": false,
    },
]
