reviews_data = [
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 51466166,
        "reviewDateTime": "2021-08-22T17:06:09.807",
        "ratingOverall": 5,
        "ratingCeo": None,
        "ratingBusinessOutlook": "NEUTRAL",
        "ratingWorkLifeBalance": 5,
        "ratingCultureAndValues": 1,
        "ratingDiversityAndInclusion": 1,
        "ratingSeniorLeadership": 1,
        "ratingRecommendToFriend": "POSITIVE",
        "ratingCareerOpportunities": 5,
        "ratingCompensationAndBenefits": 1,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": False,
        "lengthOfEmployment": 0,
        "employmentStatus": "REGULAR",
        "jobEndingYear": 2020,
        "jobTitle": {"__ref": "JobTitle:15225"},
        "location": {"__ref": "City:1146962"},
        "originalLanguageId": None,
        "pros": "I got the chance to learn and explore around different sectors, and innovations. The working environment was conducive for accelerating teamwork and productivity. I'm glad I work there.",
        "prosOriginal": None,
        "cons": "I believe there should more employment benefits targeted towards life warfare and wellness.",
        "consOriginal": None,
        "summary": "Top Notch Company To Build Career Growth And Wealth.",
        "summaryOriginal": None,
        "advice": None,
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 0,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 1,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 75326296,
        "reviewDateTime": "2023-04-09T13:00:31.367",
        "ratingOverall": 2,
        "ratingCeo": None,
        "ratingBusinessOutlook": None,
        "ratingWorkLifeBalance": 0,
        "ratingCultureAndValues": 0,
        "ratingDiversityAndInclusion": 0,
        "ratingSeniorLeadership": 0,
        "ratingRecommendToFriend": None,
        "ratingCareerOpportunities": 0,
        "ratingCompensationAndBenefits": 0,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": True,
        "lengthOfEmployment": 0,
        "employmentStatus": "CONTRACT",
        "jobEndingYear": None,
        "jobTitle": None,
        "location": {"__ref": "City:1132348"},
        "originalLanguageId": None,
        "pros": "The pay was subpar at best.",
        "prosOriginal": None,
        "cons": "They could offer remote work",
        "consOriginal": None,
        "summary": "it's okay",
        "summaryOriginal": None,
        "advice": None,
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 0,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 3,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 77956742,
        "reviewDateTime": "2023-07-04T14:14:12.290",
        "ratingOverall": 5,
        "ratingCeo": None,
        "ratingBusinessOutlook": "NEUTRAL",
        "ratingWorkLifeBalance": 5,
        "ratingCultureAndValues": 5,
        "ratingDiversityAndInclusion": 5,
        "ratingSeniorLeadership": 4,
        "ratingRecommendToFriend": "POSITIVE",
        "ratingCareerOpportunities": 4,
        "ratingCompensationAndBenefits": 4,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": False,
        "lengthOfEmployment": 2,
        "employmentStatus": "REGULAR",
        "jobEndingYear": 2019,
        "jobTitle": {"__ref": "JobTitle:44045"},
        "location": {"__ref": "City:2671300"},
        "originalLanguageId": None,
        "pros": "Great place to work and a great company to grow with",
        "prosOriginal": None,
        "cons": "No real issues working here",
        "consOriginal": None,
        "summary": "Great place to work",
        "summaryOriginal": None,
        "advice": None,
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 0,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 2,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 70112029,
        "reviewDateTime": "2022-10-13T09:35:20.397",
        "ratingOverall": 1,
        "ratingCeo": None,
        "ratingBusinessOutlook": None,
        "ratingWorkLifeBalance": 0,
        "ratingCultureAndValues": 0,
        "ratingDiversityAndInclusion": 0,
        "ratingSeniorLeadership": 0,
        "ratingRecommendToFriend": None,
        "ratingCareerOpportunities": 0,
        "ratingCompensationAndBenefits": 0,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": False,
        "lengthOfEmployment": 1,
        "employmentStatus": "REGULAR",
        "jobEndingYear": 2022,
        "jobTitle": {"__ref": "JobTitle:50731"},
        "location": {"__ref": "City:2675154"},
        "originalLanguageId": None,
        "pros": "The office location is lovely",
        "prosOriginal": None,
        "cons": "- Too many product issues. Departments are all understaffed so it is taking longer than necessary for issues to be resolved. \r\n- No processes to resolve said issues. Each problem is continuously passed on from department to department. \r\n- Base salary is far too low compared to job expectations. \r\n- No mention of support for Black History Month, yet other minority months are supported. \r\n- Expected to charge accounts a certain rate for packages, but then too many discounts are applied. \r\n- They refuse to increase the salary but put a job posting out offering more than the basic salary for Senior Account Managers. \r\n- There isn’t enough time to train the new starters. \r\n- There’s an internal training scheme for staff who are interested in becoming managers, but if you miss a session (a single session) due to situations out of your control, you’re taken off the course. \r\n- Overall completely unorganised, unprofessional company.",
        "consOriginal": None,
        "summary": "Wouldn’t recommend…",
        "summaryOriginal": None,
        "advice": "- If you believe that your product works then why are you allowing so many discounts to be applied to packages? \r\n- Why aren’t teams made aware of the emails that are sent to customers? \r\n- Acknowledge the Senior job posting in company meetings properly. You have dealt with it in a very sly manner. \r\n- Be clear on what you expect Account Managers to prioritise. \r\n- Create a better training plan for new starters and the management course \r\n- Basic salary increase",
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 1,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 1,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 75146890,
        "reviewDateTime": "2023-04-03T10:29:46.420",
        "ratingOverall": 3,
        "ratingCeo": None,
        "ratingBusinessOutlook": None,
        "ratingWorkLifeBalance": 0,
        "ratingCultureAndValues": 0,
        "ratingDiversityAndInclusion": 0,
        "ratingSeniorLeadership": 0,
        "ratingRecommendToFriend": None,
        "ratingCareerOpportunities": 0,
        "ratingCompensationAndBenefits": 0,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": False,
        "lengthOfEmployment": 4,
        "employmentStatus": "REGULAR",
        "jobEndingYear": 2021,
        "jobTitle": {"__ref": "JobTitle:15225"},
        "location": {"__ref": "City:3380432"},
        "originalLanguageId": None,
        "pros": "Friendly atmosphere and well supplied offices",
        "prosOriginal": None,
        "cons": "Not great accountability for management",
        "consOriginal": None,
        "summary": "Nice enough",
        "summaryOriginal": None,
        "advice": None,
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 0,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 2,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 74453879,
        "reviewDateTime": "2023-03-13T04:53:37.343",
        "ratingOverall": 3,
        "ratingCeo": None,
        "ratingBusinessOutlook": "POSITIVE",
        "ratingWorkLifeBalance": 3,
        "ratingCultureAndValues": 3,
        "ratingDiversityAndInclusion": 3,
        "ratingSeniorLeadership": 3,
        "ratingRecommendToFriend": "POSITIVE",
        "ratingCareerOpportunities": 2,
        "ratingCompensationAndBenefits": 3,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": False,
        "lengthOfEmployment": 1,
        "employmentStatus": "REGULAR",
        "jobEndingYear": 2023,
        "jobTitle": {"__ref": "JobTitle:50838"},
        "location": {"__ref": "City:2671300"},
        "originalLanguageId": None,
        "pros": "Working from home 3 days a week",
        "prosOriginal": None,
        "cons": "Cold calling and job repetition. Also no room for progression",
        "consOriginal": None,
        "summary": "Emg",
        "summaryOriginal": None,
        "advice": None,
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 0,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 2,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 71669873,
        "reviewDateTime": "2022-12-06T16:40:52.667",
        "ratingOverall": 1,
        "ratingCeo": None,
        "ratingBusinessOutlook": "NEGATIVE",
        "ratingWorkLifeBalance": 1,
        "ratingCultureAndValues": 1,
        "ratingDiversityAndInclusion": 1,
        "ratingSeniorLeadership": 1,
        "ratingRecommendToFriend": "NEGATIVE",
        "ratingCareerOpportunities": 1,
        "ratingCompensationAndBenefits": 1,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": False,
        "lengthOfEmployment": 1,
        "employmentStatus": "REGULAR",
        "jobEndingYear": 2022,
        "jobTitle": {"__ref": "JobTitle:270488"},
        "location": {"__ref": "City:2675154"},
        "originalLanguageId": None,
        "pros": "My team, stocked fridge during office days and hybrid work from home",
        "prosOriginal": None,
        "cons": "Management - they do not treat you as employees but rather as robots who they don’t want to have any personality. Your main job is to answer phones, this job is a glorified call centre but the job description will tell you otherwise. You are not allowed to take lunch as a team, you’re not allowed to attend company wide meetings as a team, all because you are constantly asked to stay on the phones at all time, management will make you feel bad about going to the bathroom or grabbing a coffee.",
        "consOriginal": None,
        "summary": "Avoid if you care about your mental well-being",
        "summaryOriginal": None,
        "advice": "Take your feedback on board, there is a reason this company was failing and such need for these drastic changes. Your employees are not robots, treat them with divinity!",
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 1,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 2,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 73117556,
        "reviewDateTime": "2023-01-29T23:30:26.573",
        "ratingOverall": 1,
        "ratingCeo": None,
        "ratingBusinessOutlook": "NEGATIVE",
        "ratingWorkLifeBalance": 1,
        "ratingCultureAndValues": 1,
        "ratingDiversityAndInclusion": 1,
        "ratingSeniorLeadership": 1,
        "ratingRecommendToFriend": "NEGATIVE",
        "ratingCareerOpportunities": 1,
        "ratingCompensationAndBenefits": 1,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": True,
        "lengthOfEmployment": 2,
        "employmentStatus": "REGULAR",
        "jobEndingYear": None,
        "jobTitle": {"__ref": "JobTitle:270488"},
        "location": {"__ref": "City:2675154"},
        "originalLanguageId": None,
        "pros": "Office location was really nice",
        "prosOriginal": None,
        "cons": "If you are a honest person just trying to make a living, avoid this place like the plague. Business built upon manipulative management that refuse to be honest with you. Customer Service role disguised as customer success role to bring in more recruitment however you are stalling your own career progression as nothing about this role is customer success related. No matter what you do, your value as an employee is measured by inbound call rates. No motivation or morale building, however management quick to talk down on you when one call is missed during busy periods with less than normal staff. Refusing to give promotions but advertising roles at higher salary and claim that these are in line with their competency framework, however belittle and gaslight you when you show examples of this. The minute you show any autonomy or progression management look for ways to shift the goalpost so you look like you’re underperforming and a way to push you out No training in place so all left to team members to support and train new staff, because both team lead and managers ignore your messages all day, but then they berate you for sending too many messages. Refusal to listen about ways to improve service or product, look at you like a number rather than an employee to be spoken at - this is not a collaborative environment at all Include technical errors such as phone cut outs or automatic case raising when kpi measuring so you never reach your target for bonus Don’t speak to HR about anything you’re worried about as in turn management will retaliate and team leads in different departments will know about it and make you feel like you’re in the wrong Management try and act intimidating the minute you speak out about things that aren’t right within the business There is constantly a scapegoat as management and team leads will never take responsibility as this makes them look bad to the investors You’re told that you do not deserve pay rises and that no progression can be offered",
        "consOriginal": None,
        "summary": "Avoid this place if you value yourself",
        "summaryOriginal": None,
        "advice": "Look at all the cons and figure it out yourself the same way your staff have to figure everything out themselves.",
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 6,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 2,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 69406948,
        "reviewDateTime": "2022-09-24T10:22:52.130",
        "ratingOverall": 5,
        "ratingCeo": "APPROVE",
        "ratingBusinessOutlook": "POSITIVE",
        "ratingWorkLifeBalance": 4,
        "ratingCultureAndValues": 3,
        "ratingDiversityAndInclusion": 3,
        "ratingSeniorLeadership": 3,
        "ratingRecommendToFriend": "POSITIVE",
        "ratingCareerOpportunities": 5,
        "ratingCompensationAndBenefits": 4,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": False,
        "lengthOfEmployment": 0,
        "employmentStatus": "REGULAR",
        "jobEndingYear": 2020,
        "jobTitle": None,
        "location": None,
        "originalLanguageId": None,
        "pros": "Good people working at this company",
        "prosOriginal": None,
        "cons": "The bar on performance is set very high",
        "consOriginal": None,
        "summary": "Good stuff",
        "summaryOriginal": None,
        "advice": None,
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 0,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 7,
        "languageId": "eng",
        "translationMethod": None,
    },
    {
        "__typename": "EmployerReviewRG",
        "isLegal": True,
        "reviewId": 71331461,
        "reviewDateTime": "2022-11-23T06:18:03.793",
        "ratingOverall": 2,
        "ratingCeo": None,
        "ratingBusinessOutlook": None,
        "ratingWorkLifeBalance": 0,
        "ratingCultureAndValues": 0,
        "ratingDiversityAndInclusion": 0,
        "ratingSeniorLeadership": 0,
        "ratingRecommendToFriend": None,
        "ratingCareerOpportunities": 0,
        "ratingCompensationAndBenefits": 0,
        "employer": {"__ref": "Employer:4189745"},
        "isCurrentJob": False,
        "lengthOfEmployment": 0,
        "employmentStatus": "REGULAR",
        "jobEndingYear": 2021,
        "jobTitle": {"__ref": "JobTitle:15225"},
        "location": {"__ref": "City:2671300"},
        "originalLanguageId": None,
        "pros": "Nice people and good perks",
        "prosOriginal": None,
        "cons": "Management was poor. Moving targets and just tell you try harder.",
        "consOriginal": None,
        "summary": "Poor management",
        "summaryOriginal": None,
        "advice": None,
        "adviceOriginal": None,
        "isLanguageMismatch": False,
        "countHelpful": 0,
        "countNotHelpful": 0,
        "employerResponses": [],
        "featured": False,
        "isCovid19": False,
        "topLevelDomainId": 1,
        "languageId": "eng",
        "translationMethod": None,
    },
]


#######################################################################################################################################


reviews = {
    51466166: {
        "review_id": 51466166,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2021, 8, 22, 17, 6, 9, 807000),
        "rating_overall": 5,
        "rating_ceo": None,
        "rating_business_outlook": "NEUTRAL",
        "rating_work_life_balance": 5,
        "rating_culture_and_values": 1,
        "rating_diversity_and_inclusion": 1,
        "rating_senior_seadership": 1,
        "rating_recommend_to_friend": "POSITIVE",
        "rating_career_opportunities": 5,
        "rating_compensation_and_benefits": 1,
        "is_current_job": False,
        "length_of_employment": 0,
        "employment_status": "REGULAR",
        "job_ending_year": 2020,
        "job_title": "Account Manager",
        "location": "American Canyon, CA",
        "pros": "I got the chance to learn and explore around different sectors, and innovations. The working environment was conducive for accelerating teamwork and productivity. I'm glad I work there.",
        "cons": "I believe there should more employment benefits targeted towards life warfare and wellness.",
        "summary": "Top Notch Company To Build Career Growth And Wealth.",
        "advice": None,
        "count_helpful": 0,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    75326296: {
        "review_id": 75326296,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2023, 4, 9, 13, 0, 31, 367000),
        "rating_overall": 2,
        "rating_ceo": None,
        "rating_business_outlook": None,
        "rating_work_life_balance": 0,
        "rating_culture_and_values": 0,
        "rating_diversity_and_inclusion": 0,
        "rating_senior_seadership": 0,
        "rating_recommend_to_friend": None,
        "rating_career_opportunities": 0,
        "rating_compensation_and_benefits": 0,
        "is_current_job": True,
        "length_of_employment": 0,
        "employment_status": "CONTRACT",
        "job_ending_year": None,
        "job_title": None,
        "location": "New York, NY",
        "pros": "The pay was subpar at best.",
        "cons": "They could offer remote work",
        "summary": "it's okay",
        "advice": None,
        "count_helpful": 0,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    70112029: {
        "review_id": 70112029,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2022, 10, 13, 9, 35, 20, 397000),
        "rating_overall": 1,
        "rating_ceo": None,
        "rating_business_outlook": None,
        "rating_work_life_balance": 0,
        "rating_culture_and_values": 0,
        "rating_diversity_and_inclusion": 0,
        "rating_senior_seadership": 0,
        "rating_recommend_to_friend": None,
        "rating_career_opportunities": 0,
        "rating_compensation_and_benefits": 0,
        "is_current_job": False,
        "length_of_employment": 1,
        "employment_status": "REGULAR",
        "job_ending_year": 2022,
        "job_title": "Sales Account Manager",
        "location": "Richmond, London, England",
        "pros": "The office location is lovely",
        "cons": "- Too many product issues. Departments are all understaffed so it is taking longer than necessary for issues to be resolved. \r\n- No processes to resolve said issues. Each problem is continuously passed on from department to department. \r\n- Base salary is far too low compared to job expectations. \r\n- No mention of support for Black History Month, yet other minority months are supported. \r\n- Expected to charge accounts a certain rate for packages, but then too many discounts are applied. \r\n- They refuse to increase the salary but put a job posting out offering more than the basic salary for Senior Account Managers. \r\n- There isn’t enough time to train the new starters. \r\n- There’s an internal training scheme for staff who are interested in becoming managers, but if you miss a session (a single session) due to situations out of your control, you’re taken off the course. \r\n- Overall completely unorganised, unprofessional company.",
        "summary": "Wouldn’t recommend…",
        "advice": "- If you believe that your product works then why are you allowing so many discounts to be applied to packages? \r\n- Why aren’t teams made aware of the emails that are sent to customers? \r\n- Acknowledge the Senior job posting in company meetings properly. You have dealt with it in a very sly manner. \r\n- Be clear on what you expect Account Managers to prioritise. \r\n- Create a better training plan for new starters and the management course \r\n- Basic salary increase",
        "count_helpful": 1,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    77956742: {
        "review_id": 77956742,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2023, 7, 4, 14, 14, 12, 290000),
        "rating_overall": 5,
        "rating_ceo": None,
        "rating_business_outlook": "NEUTRAL",
        "rating_work_life_balance": 5,
        "rating_culture_and_values": 5,
        "rating_diversity_and_inclusion": 5,
        "rating_senior_seadership": 4,
        "rating_recommend_to_friend": "POSITIVE",
        "rating_career_opportunities": 4,
        "rating_compensation_and_benefits": 4,
        "is_current_job": False,
        "length_of_employment": 2,
        "employment_status": "REGULAR",
        "job_ending_year": 2019,
        "job_title": "Sales Ops",
        "location": "London, England",
        "pros": "Great place to work and a great company to grow with",
        "cons": "No real issues working here",
        "summary": "Great place to work",
        "advice": None,
        "count_helpful": 0,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    71669873: {
        "review_id": 71669873,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2022, 12, 6, 16, 40, 52, 667000),
        "rating_overall": 1,
        "rating_ceo": None,
        "rating_business_outlook": "NEGATIVE",
        "rating_work_life_balance": 1,
        "rating_culture_and_values": 1,
        "rating_diversity_and_inclusion": 1,
        "rating_senior_seadership": 1,
        "rating_recommend_to_friend": "NEGATIVE",
        "rating_career_opportunities": 1,
        "rating_compensation_and_benefits": 1,
        "is_current_job": False,
        "length_of_employment": 1,
        "employment_status": "REGULAR",
        "job_ending_year": 2022,
        "job_title": "Customer Success Executive",
        "location": "Richmond, London, England",
        "pros": "My team, stocked fridge during office days and hybrid work from home",
        "cons": "Management - they do not treat you as employees but rather as robots who they don’t want to have any personality. Your main job is to answer phones, this job is a glorified call centre but the job description will tell you otherwise. You are not allowed to take lunch as a team, you’re not allowed to attend company wide meetings as a team, all because you are constantly asked to stay on the phones at all time, management will make you feel bad about going to the bathroom or grabbing a coffee.",
        "summary": "Avoid if you care about your mental well-being",
        "advice": "Take your feedback on board, there is a reason this company was failing and such need for these drastic changes. Your employees are not robots, treat them with divinity!",
        "count_helpful": 1,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    73117556: {
        "review_id": 73117556,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2023, 1, 29, 23, 30, 26, 573000),
        "rating_overall": 1,
        "rating_ceo": None,
        "rating_business_outlook": "NEGATIVE",
        "rating_work_life_balance": 1,
        "rating_culture_and_values": 1,
        "rating_diversity_and_inclusion": 1,
        "rating_senior_seadership": 1,
        "rating_recommend_to_friend": "NEGATIVE",
        "rating_career_opportunities": 1,
        "rating_compensation_and_benefits": 1,
        "is_current_job": True,
        "length_of_employment": 2,
        "employment_status": "REGULAR",
        "job_ending_year": None,
        "job_title": "Customer Success Executive",
        "location": "Richmond, London, England",
        "pros": "Office location was really nice",
        "cons": "If you are a honest person just trying to make a living, avoid this place like the plague. Business built upon manipulative management that refuse to be honest with you. Customer Service role disguised as customer success role to bring in more recruitment however you are stalling your own career progression as nothing about this role is customer success related. No matter what you do, your value as an employee is measured by inbound call rates. No motivation or morale building, however management quick to talk down on you when one call is missed during busy periods with less than normal staff. Refusing to give promotions but advertising roles at higher salary and claim that these are in line with their competency framework, however belittle and gaslight you when you show examples of this. The minute you show any autonomy or progression management look for ways to shift the goalpost so you look like you’re underperforming and a way to push you out No training in place so all left to team members to support and train new staff, because both team lead and managers ignore your messages all day, but then they berate you for sending too many messages. Refusal to listen about ways to improve service or product, look at you like a number rather than an employee to be spoken at - this is not a collaborative environment at all Include technical errors such as phone cut outs or automatic case raising when kpi measuring so you never reach your target for bonus Don’t speak to HR about anything you’re worried about as in turn management will retaliate and team leads in different departments will know about it and make you feel like you’re in the wrong Management try and act intimidating the minute you speak out about things that aren’t right within the business There is constantly a scapegoat as management and team leads will never take responsibility as this makes them look bad to the investors You’re told that you do not deserve pay rises and that no progression can be offered",
        "summary": "Avoid this place if you value yourself",
        "advice": "Look at all the cons and figure it out yourself the same way your staff have to figure everything out themselves.",
        "count_helpful": 6,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    75146890: {
        "review_id": 75146890,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2023, 4, 3, 10, 29, 46, 420000),
        "rating_overall": 3,
        "rating_ceo": None,
        "rating_business_outlook": None,
        "rating_work_life_balance": 0,
        "rating_culture_and_values": 0,
        "rating_diversity_and_inclusion": 0,
        "rating_senior_seadership": 0,
        "rating_recommend_to_friend": None,
        "rating_career_opportunities": 0,
        "rating_compensation_and_benefits": 0,
        "is_current_job": False,
        "length_of_employment": 4,
        "employment_status": "REGULAR",
        "job_ending_year": 2021,
        "job_title": "Account Manager",
        "location": "Abingdon, England",
        "pros": "Friendly atmosphere and well supplied offices",
        "cons": "Not great accountability for management",
        "summary": "Nice enough",
        "advice": None,
        "count_helpful": 0,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    74453879: {
        "review_id": 74453879,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2023, 3, 13, 4, 53, 37, 343000),
        "rating_overall": 3,
        "rating_ceo": None,
        "rating_business_outlook": "POSITIVE",
        "rating_work_life_balance": 3,
        "rating_culture_and_values": 3,
        "rating_diversity_and_inclusion": 3,
        "rating_senior_seadership": 3,
        "rating_recommend_to_friend": "POSITIVE",
        "rating_career_opportunities": 2,
        "rating_compensation_and_benefits": 3,
        "is_current_job": False,
        "length_of_employment": 1,
        "employment_status": "REGULAR",
        "job_ending_year": 2023,
        "job_title": "Sales Associate",
        "location": "London, England",
        "pros": "Working from home 3 days a week",
        "cons": "Cold calling and job repetition. Also no room for progression",
        "summary": "Emg",
        "advice": None,
        "count_helpful": 0,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    71331461: {
        "review_id": 71331461,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2022, 11, 23, 6, 18, 3, 793000),
        "rating_overall": 2,
        "rating_ceo": None,
        "rating_business_outlook": None,
        "rating_work_life_balance": 0,
        "rating_culture_and_values": 0,
        "rating_diversity_and_inclusion": 0,
        "rating_senior_seadership": 0,
        "rating_recommend_to_friend": None,
        "rating_career_opportunities": 0,
        "rating_compensation_and_benefits": 0,
        "is_current_job": False,
        "length_of_employment": 0,
        "employment_status": "REGULAR",
        "job_ending_year": 2021,
        "job_title": "Account Manager",
        "location": "London, England",
        "pros": "Nice people and good perks",
        "cons": "Management was poor. Moving targets and just tell you try harder.",
        "summary": "Poor management",
        "advice": None,
        "count_helpful": 0,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
    62903465: {
        "review_id": 62903465,
        "employer_id": 4189745,
        "date_time": datetime.datetime(2022, 4, 18, 2, 38, 16, 430000),
        "rating_overall": 1,
        "rating_ceo": None,
        "rating_business_outlook": "NEGATIVE",
        "rating_work_life_balance": 5,
        "rating_culture_and_values": 3,
        "rating_diversity_and_inclusion": 3,
        "rating_senior_seadership": 1,
        "rating_recommend_to_friend": "NEGATIVE",
        "rating_career_opportunities": 1,
        "rating_compensation_and_benefits": 2,
        "is_current_job": False,
        "length_of_employment": 1,
        "employment_status": "REGULAR",
        "job_ending_year": 2022,
        "job_title": "Account Manager",
        "location": None,
        "pros": "Wage and commission not bad\r\nWorking from home",
        "cons": "- Senior staff do not listen to workers about how the company could improve \r\n- Set unrealistic targets without having an actual understanding of what is going on in the market \r\n- Put stupid pressure on us to overperform instead of exploring how they could make their product better \r\n- Expecting us to sell the ‘value’ of what is provided, what value if you have more cancelling accounts than accounts that join &amp; constant forum posts about how bad the product is",
        "summary": "The never listen to recommendations, they seem to think the product is better than it is",
        "advice": "LISTEN to your staff, you treat them incredibly minuscule and act as if their opinion doesn’t count. The company turnover is horrendous, so many people leave and join. Maybe train people better rather than expect magic from nothing",
        "count_helpful": 1,
        "count_not_helpful": 0,
        "is_covid19": False,
    },
}


#######################################################################################################################################


overview = {
    "employer_id": 4189745,
    "number_of_pages": 2,
    "all_reviews_count": 16,
    "rated_reviews_count": 16,
    "overall_rating": 2.8,
    "ceo_name": None,
    "ceo_rating": -1,
    "recommend_to_friend_rating": 0.59,
    "culture_and_values_rating": 2.9,
    "diversity_and_inclusion_rating": 3,
    "career_opportunities_rating": 3.2,
    "work_life_balance_rating": 3.7,
    "senior_management_rating": 2.8,
    "compensation_and_benefits_rating": 2.8,
    "business_outlook_rating": 0.4,
}
